@startuml
title Диаграмма активности: Расчет числа Фибоначчи


|Пользователь|
start
:Ввести значение n;


|Система|
:1. Проверить ввод;
if (Ввод корректен?) then (да)
  :Индекс n;
  :2. Расчитать результат;
  
  if (Значение уже есть в истории?) then (да)
    :Получить "Ранее выполненные вычисления";
  else (нет)
    :Вычислить новое Число Фибоначчи;
    :Запись вычисленных значений в Историю;
  endif
  
  :3. Отобразить результат;

  |Пользователь|
  :Получить результат вычислений;
else (нет)

  |Система|
  :Сформировать сообщение об ошибке;
  :3. Отобразить результат;

  |Пользователь|
  :Увидеть причину ошибки;
endif

stop
@enduml
