@startuml
skinparam backgroundColor white

actor "Пользователь" as User

    usecase "P1: Редактировать\nсодержимое шаблона" as P1
    usecase "P2: Проверить лимит\n(n <= 100)" as P2
    usecase "P3: Сохранить\nструктуру проекта" as P3


database "Хранилище проектов" as DB

User --> P1 : Данные UI-компонентов
P1 --> P2 : Запрос на регистрацию\nнового шаблона
P2 --> DB : Запросить текущее\nколичество (n)
DB --> P2 : Текущее n
P2 --> User : Уведомить об ошибке\n(если n >= 100)
P2 --> P3 : Передать данные\n(если n < 100)
P3 --> DB : Записать JSON-объект
@enduml
